### ISSUE TITLE
TopLevelLookupException: Can not locate template for uri 'webdnsmasq:home.mako'

### ISSUE THREAD

**Issue by h6w** [TimJuni/webdnsmasq#1]
I'm attempting to run this in an isolated instance of Alpine Linux.

I've followed the instructions as indicated.  Here's my install script:

```
apk add --no-cache python py-setuptools git
mkdir -p /opt; cd /opt; pyvenv env; cd env; git clone https://github.com/TimJuni/webdnsmasq.git
cd /opt/env/webdnsmasq && python setup.py develop
pserve production.ini

```

However, when I run this, I get the following error:

```
Starting server in PID 24.
serving on http://0.0.0.0:6543
2016-04-29 02:26:08,811 ERROR [waitress][waitress] Exception when serving /
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/waitress-0.9.0-py2.7.egg/waitress/channel.py", line 338, in service
    task.service()
  File "/usr/lib/python2.7/site-packages/waitress-0.9.0-py2.7.egg/waitress/task.py", line 169, in service
    self.execute()
  File "/usr/lib/python2.7/site-packages/waitress-0.9.0-py2.7.egg/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/usr/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/router.py", line 158, in handle_request
    view_name
  File "/usr/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/view.py", line 546, in _call_view
    response = view_callable(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/viewderivers.py", line 448, in rendered_view
    request, result, view_inst, context)
  File "/usr/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/renderers.py", line 432, in render_view
    return self.render_to_response(response, system, request=request)
  File "/usr/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/renderers.py", line 455, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/usr/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/renderers.py", line 451, in render
    result = renderer(value, system_values)
  File "/usr/lib/python2.7/site-packages/pyramid_mako-1.0.2-py2.7.egg/pyramid_mako/__init__.py", line 144, in __call__
    template = self.template
  File "/usr/lib/python2.7/site-packages/pyramid_mako-1.0.2-py2.7.egg/pyramid_mako/__init__.py", line 117, in template
    template = self.lookup.get_template(spec)
  File "/usr/lib/python2.7/site-packages/pyramid_mako-1.0.2-py2.7.egg/pyramid_mako/__init__.py", line 75, in get_template
    "Can not locate template for uri %r" % uri)
TopLevelLookupException: Can not locate template for uri 'webdnsmasq:home.mako'
^C/opt/env/webdnsmasq #

```

As far as I can tell, the templates are in /opt/env/webdnsmasq/webdnsmasq/templates.  There is a file called "home.mako".

Why can pyramid not find them?

**Comment by h6w** [comment]
Ah, apparently there's a difference between the development.ini and production.ini that is important.

If I insert the following line under "wsgi configuration", everything works:

```

mako.directories = webdnsmasq:templates

```
